# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4cb912bd0b9ca69855b570775a9c0843d4225f15012e3b52080d23b389db49a58ae2f3e01949ea3424ca986ed317da5879c68be444f2009ff73b0212e0cc8f0

test:
  secret_key_base: 9df0404fa0727d033156f72275560ed32bab558861c322b7991459e45ce6264505389bccbf61a07f35d83b16ddaea51c0e3af1924a923e1473cac20e69f0fe9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
